version: "3.8"
services:
 web:
     #build: api/
     #image: dgproviderapi:1.0.0
     container_name: web
     image: itechglobal/public:itech-web
     ports:
      - "3000:3000"
 nginx:
    #build: web/
    #image: dgproviderweb:1.0.0
    container_name: nginx
    image: itechglobal/public:itech-nginx
    ports:
      - "80:80"
    depends_on:
      - web
 #nginx:
  #image: "dgprovider-nginx:1.0.0"
  #image: "itechglobalregistry.azurecr.io/dgprovider-nginx:1.0.0"
  #depends_on:
  #  - web
  #networks:
  #  - sub-etha
  #ports:
  #  - "80:80"